-- users Table  
CREATE TABLE useerss_ (
    user_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    password VARCHAR(100),
    email VARCHAR(100) UNIQUE,
    full_name VARCHAR(100),
    date_of_birth DATE,
    phone_number VARCHAR(20),
    role VARCHAR(20)
);
-- Classes Table 
CREATE TABLE Classes__ (
    class_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    class_name VARCHAR(20) NOT NULL,
    day VARCHAR(100),
    time VARCHAR(100),
    max_capacity NUMBER(2),
    trainer_id NUMBER,
    FOREIGN KEY (trainer_id) REFERENCES useerss_(user_id)
);
-- Service Table 
CREATE TABLE services (
    service_name VARCHAR(20)
);

-- Offer Table
CREATE TABLE Offer (
    coupon VARCHAR2(50),
    occasion VARCHAR2(100),
    discount VARCHAR2(10),
    expireDate VARCHAR2(10)
);

-- track Progres Table
CREATE TABLE traProgres__ (
    member_id NUMBER NOT NULL,
    weight NUMBER(5, 2),
    height NUMBER(5, 2),
    MusclePercentage VARCHAR2(10),
    FatPercentage VARCHAR2(10),
    FOREIGN KEY (member_id) REFERENCES useerss_(user_id)
);

